#
#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

live_config_reload: true

env:
  TERM: xterm-256color

window:
  decorations: buttonless
  dynamic_padding: false
  opacity: 0.9
  padding:
    x: 8 
    y: 8

font:
  normal:
    family: "MesloLGS NF"
    style: Regular
  italic:
    family: "MesloLGS NF"
    style: Italic
  bold:
    family: "MesloLGS NF"
    style: Bold
  bold_italic:
    family: "MesloLGS NF"
    style: Bold Italic
  size: 18.0

# NOTE: helpful hex codes
# \x1b = escape (useful for vim-related keybindings)
# \x00 = control-space (the tmux prefix)

key_bindings:
  - { key: E, mods: Command, chars: "\x00\"" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x00%" } # split tmux window horizontally
  - { key: F, mods: Command|Shift, chars: "\x00\x5b\x2f" } # start tmux search mode

  # - { key: G, mods: Command, chars: "\x00g" } # open git manager 'jesseduffield/lazygit'
  # - { key: O, mods: Command, chars: "\x00u" } # open URLs 'joshmedeski/tmux-fzf-url'

  - { key: J, mods: Command, chars: "\x00\x54" } # open t - tmux smart session manager
  - { key: K, mods: Command, chars: "\x00\x54" } # open t - tmux smart session manager
  - { key: L, mods: Command, chars: "\x00L" } # switch to the last tmux session
  - { key: P, mods: Command, chars: ":GoToFile\n" } # go to file
  - { key: P, mods: Command|Shift, chars: ":GoToCommand\n" } # run command
  - { key: Q, mods: Command, chars: ":q\n" } # quit vim
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # save vim buffer
  - { key: T, mods: Command, chars: "\x00c" } # create a new tmux window
  - { key: T, mods: Command|Shift, chars: "\x00P" } #                ... Toggle Pomodoro
  - { key: W, mods: Command, chars: "\x00x" } # kill the current pane
  - { key: Z, mods: Command, chars: "\x00z" } # toggle zoom state of the current tmux pane
  - { key: Tab, mods: Control, chars: "\x00n" } # switch to next tmux window
  - { key: Grave, mods: Control, chars: "\x00p" } # switch to previous tmux window
  - { key: Comma, mods: Command, chars: "\x00," } # rename the current tmux window
  - { key: LBracket, mods: Command, chars: "\x0f" } # navigate back in vim (ctrl+o)
  - { key: LBracket, mods: Command|Shift, chars: "\x00p" } # switch to next tmux window
  - { key: RBracket, mods: Command, chars: "\x09" } # navigate forward in vim (ctrl+i)
  - { key: RBracket, mods: Command|Shift, chars: "\x00n" } # switch to previous tmux window
  - { key: Semicolon, mods: Command, chars: "\x00:" } # enter the tmux command prompt
  - { key: Key1, mods: Command, chars: "\x001" } # select tmux window 1
  - { key: Key2, mods: Command, chars: "\x002" } #                ... 2
  - { key: Key3, mods: Command, chars: "\x003" } #                ... 3
  - { key: Key4, mods: Command, chars: "\x004" } #                ... 4
  - { key: Key5, mods: Command, chars: "\x005" } #                ... 5
  - { key: Key6, mods: Command, chars: "\x006" } #                ... 6
  - { key: Key7, mods: Command, chars: "\x007" } #                ... 7
  - { key: Key8, mods: Command, chars: "\x008" } #                ... 8
  - { key: Key9, mods: Command, chars: "\x009" } #                ... 9