local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', function() 
	builtin.find_files({ })
end, {}) 
vim.keymap.set('n', '<leader>ff', function() 
	builtin.find_files({ hidden = true })
end, {}) 
vim.keymap.set('n', '<leader>pp', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
